export interface Producto{
    index:number,
    batch:string,
    codBarra:string,
    dateRegistre:string,
    idProducto:number,
    idSupplier:number,
    line:string,
    mark:string,
    nameProduto:string,
    notafiscal:string,
    pricePurchase:Number
    priceSales:Number
    validity:string,
    quantidadeEstoque:number;
    quant:Number;
    vTotal:Number;
    funcaoDeleteItem:Function
}